DROP TABLE IF EXISTS TOOLS;
DROP TABLE IF EXISTS TOOL_CHARGES;
CREATE TABLE TOOL_CHARGES (
TOOL_TYPE VARCHAR(20) PRIMARY KEY,
DAILY_CHARGE DECIMAL(5, 2),
WEEKDAY_CHARGE BOOLEAN,
WEEKEND_CHARGE BOOLEAN,
HOLIDAY_CHARGE BOOLEAN
);

CREATE TABLE TOOLS (
TOOL_CODE VARCHAR(10) PRIMARY KEY,
TOOL_TYPE VARCHAR(20),
BRAND VARCHAR(20),
FOREIGN KEY (TOOL_TYPE) REFERENCES TOOL_CHARGES(TOOL_TYPE)
);

CREATE INDEX IDX01_TOOL_TYPE ON TOOL_CHARGES (TOOL_TYPE);
CREATE INDEX IDX02_TOOL_CODE ON TOOLS (TOOL_CODE);
CREATE INDEX IDX03_TOOL_TYPE ON TOOLS (TOOL_TYPE);


--INSERTS
INSERT INTO TOOL_CHARGES (TOOL_TYPE, DAILY_CHARGE, WEEKDAY_CHARGE, WEEKEND_CHARGE, HOLIDAY_CHARGE) VALUES
    ('Ladder', 1.99, TRUE, TRUE, FALSE),
    ('Chainsaw', 1.49, TRUE, FALSE, TRUE),
    ('Jackhammer', 2.99, TRUE, FALSE, FALSE);

INSERT INTO TOOLS (TOOL_CODE, TOOL_TYPE, BRAND) VALUES
    ('CHNS', 'Chainsaw', 'Stihl'),
    ('LADW', 'Ladder', 'Werner'),
    ('JAKD', 'Jackhammer', 'DeWalt'),
    ('JAKR', 'Jackhammer', 'Ridgid');